services:
  - type: web
    name: bag-wiki-api
    env: docker
    repo: https://github.com/alkhatib99/bag_wiki_api_dart
    region: oregon
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgres://u293297_Be11RGKyDP:9qijZb1BEIDppU7ivJuNxLoa@gamesfra3.bisecthosting.com:5432/s293297_test
      - key: TELEGRAM_BOT_TOKEN
        value: 7659362217:AAEWZDwALfX4bCXXI3cXRUR67w5iGF-wQTQ
      - key: PORT
        value: 8080
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: https://bagwiki.vercel.app,https://bag-wiki-admin.vercel.app
