services:
  - type: web
    name: bag-wiki-api
    env: docker
    repo: https://github.com/alkhatib99/bag_wiki_api_dart
    region: oregon
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL
        value: true
      - key: PORT
        value: 8080
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: https://bag-wiki.vercel.app,https://bag-wiki-admin.vercel.app
